MachineTest/Controllers/VendorController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MachineTest.Models;
using System.Collections;

namespace MachineTest.Controllers
{
    public class VendorController : Controller
    {
        BusinessLayer objBus = new BusinessLayer();
        // GET: Vendor
        public ActionResult VendorList()
        {
            VendorModel vm = new VendorModel();
           vm=vm.GetInitialData();
            return View(vm);
        }
        [HttpGet]
        public ActionResult AddVendor(string mode, int? vendorid)
        {
            VendorModel obj = new VendorModel();
            if (mode=="U")
            {
               
                obj = obj.UpdateVendordetails(vendorid);
                DataTable dtCountry = new DataTable();
                DataTable dtPayTerms = new DataTable();
                dtCountry = objBus.GetAllCountry();
                dtPayTerms = objBus.GetPaymentTermsDay();
                ViewBag.Country = BusinessLayer.CreateDropdownList(dtCountry);
                ViewBag.PaymentTermsDay = BusinessLayer.CreateDropdownListPaymentTerms(dtPayTerms);
            }
            else
            {
               
                DataTable dtCountry = new DataTable();
                DataTable dtPayTerms = new DataTable();
                dtCountry = objBus.GetAllCountry();
                dtPayTerms = objBus.GetPaymentTermsDay();
                ViewBag.Country = BusinessLayer.CreateDropdownList(dtCountry);
                ViewBag.PaymentTermsDay = BusinessLayer.CreateDropdownListPaymentTerms(dtPayTerms);
            }
           
            return View(obj);
        }
        [HttpPost]
        public ActionResult AddVendor(VendorModel obj)
        {
            DataTable dtCountry = new DataTable();
            DataTable dtPayTerms = new DataTable();
            dtCountry = objBus.GetAllCountry();
            dtPayTerms = objBus.GetPaymentTermsDay();
            ViewBag.Country = BusinessLayer.CreateDropdownList(dtCountry);
            ViewBag.PaymentTermsDay = BusinessLayer.CreateDropdownListPaymentTerms(dtPayTerms);
            bool flag = objBus.SaveVendorDetails(obj);
            if (obj.Mode=="U" && flag==true)
            {
                ViewData["msg"] = "Vendor Data Updated Successfully...";
            }
            else
            {
                ViewData["msg"] = flag == true ? "Data Save Successfully..." : "Some Error Occured...";
            }
            
           
            return View(obj);
        }

        public string DeleteVendor(int vendorid)
        {
            bool flag = false;
            string result = "";
            if (vendorid!=null && vendorid > 0)
            {
              flag= objBus.DeleteVendor(vendorid);
            }
            result = flag == true ? "True" : "False";
            return result;
        }
    }
}

MachineTest/Views/Shared/LayoutHome.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Citytech Machine Test</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body style="overflow-x:hidden">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Vendor List", "VendorList", "Vendor")</li>
                    <li>@Html.ActionLink("Add Vendor", "AddVendor", "Vendor")</li>
                    @*<li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                </ul>
            </div>
        </div>
    </div>
    <div class="row">
        @*<div class="col-sm-1"></div>*@
        <div class="col-sm-10">
            @RenderBody()
            <hr />
            @*<footer>
                    <p>&copy; @DateTime.Now.Year - Citytech Machine Test</p>
                </footer>*@
        </div>
        @*<div class="col-sm-1"></div>*@


    </div>

    @*@Scripts.Render("~/bundles/jquery")*@
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MachineTest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Citytech Machine Test</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body style="overflow-x:hidden">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Vendor List", "VendorList", "Vendor")</li>
                    <li>@Html.ActionLink("Add Vendor", "AddVendor", "Vendor")</li>
                    @*<li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                </ul>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-1"></div>
        <div class="col-sm-10">
            @RenderBody()
                <hr />
                @*<footer>
                    <p>&copy; @DateTime.Now.Year - Citytech Machine Test</p>
                </footer>*@
            </div>
        <div class="col-sm-1"></div>
        
       
    </div>

    @*@Scripts.Render("~/bundles/jquery")*@
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>